### PR TITLE
very minor, init accepts binary strings

### PR DESCRIPTION
**Pull request by mbrix**
I think its a common use case to have the URL as a binary string, so I added a start_link clause.

### CODE REVIEW

**Comment by jeremyong** [comment]
Yes please fix the spec. Also, please reword your commit message to something that describes what you're doing more explicitly and without the editorial information.

Thanks!

**Comment by mbrix** [comment]
I added the spec change and ran Dialyzer, and change the wording without commentary.

**Comment by jeremyong** [comment]
Last thing: can you merge your commits? Compiling the first one will fail with warnings. All commits should generally be independently buildable and testable.

**Comment by mbrix** [comment]
There you go, squashed.

**Comment by jeremyong** [comment]
Thanks!

**Pull request merged**
